// plugins/withNavBarMarginsFix.js
// Expo config plugin: enforce a minimum 16pt leading/trailing margin on
// UINavigationBar so the large title never collapses to the screen edge.
//
// Root cause: react-navigation drawer wraps its content in an Animated.View
// whose non-identity CATransform3D makes iOS clear directionalLayoutMargins
// on the embedded UINavigationBar; iOS doesn't re-compute margins when the
// transform returns to identity, so the large title stays pinned to x=0.
//
// Fix: method-swizzle -[UINavigationBar layoutSubviews] to clamp the
// directional layout margins to >= 16pt after every layout pass.

const { withDangerousMod, withXcodeProject } = require("expo/config-plugins");
const fs = require("fs");
const path = require("path");

const FILE_NAME = "NavBarMarginsFix.m";

const SOURCE = `// NavBarMarginsFix.m — AUTO-GENERATED by plugins/withNavBarMarginsFix.js
// Clamp UINavigationBar.directionalLayoutMargins to a minimum of 16pt so the
// native large title never collapses to the screen edge when embedded under a
// drawer / transformed ancestor. See plugins/withNavBarMarginsFix.js for why.
#import <UIKit/UIKit.h>
#import <objc/runtime.h>

static const CGFloat kMinMargin = 16.0;

@interface UINavigationBar (ClimMateMarginsFix)
@end

@implementation UINavigationBar (ClimMateMarginsFix)

+ (void)load {
  static dispatch_once_t onceToken;
  dispatch_once(&onceToken, ^{
    Class cls = [self class];
    SEL original = @selector(layoutSubviews);
    SEL swizzled = @selector(climmate_layoutSubviews);
    Method originalMethod = class_getInstanceMethod(cls, original);
    Method swizzledMethod = class_getInstanceMethod(cls, swizzled);
    method_exchangeImplementations(originalMethod, swizzledMethod);
  });
}

- (void)climmate_layoutSubviews {
  [self climmate_layoutSubviews]; // calls the original via swizzled pair
  NSDirectionalEdgeInsets insets = self.directionalLayoutMargins;
  BOOL needsUpdate = NO;
  if (insets.leading < kMinMargin) {
    insets.leading = kMinMargin;
    needsUpdate = YES;
  }
  if (insets.trailing < kMinMargin) {
    insets.trailing = kMinMargin;
    needsUpdate = YES;
  }
  if (needsUpdate) {
    self.directionalLayoutMargins = insets;
  }
}

@end
`;

const withCopyFile = (config) => {
  return withDangerousMod(config, [
    "ios",
    async (cfg) => {
      const iosDir = cfg.modRequest.platformProjectRoot;
      const targetName = cfg.modRequest.projectName;
      const dest = path.join(iosDir, targetName, FILE_NAME);
      fs.writeFileSync(dest, SOURCE, "utf-8");
      return cfg;
    },
  ]);
};

const withRegisterFile = (config) => {
  return withXcodeProject(config, (cfg) => {
    const project = cfg.modResults;
    const targetName = cfg.modRequest.projectName;
    const groupName = targetName;

    const group = project.pbxGroupByName(groupName);
    if (!group) {
      return cfg;
    }

    // Check if already added
    const pbxGroup = project.getPBXGroupByKey(
      project.findPBXGroupKey({ name: groupName })
    );
    const alreadyAdded = (pbxGroup?.children || []).some(
      (child) => child.comment === FILE_NAME
    );
    if (alreadyAdded) {
      return cfg;
    }

    project.addSourceFile(
      `${targetName}/${FILE_NAME}`,
      { target: project.getFirstTarget().uuid },
      project.findPBXGroupKey({ name: groupName })
    );

    return cfg;
  });
};

module.exports = (config) => {
  config = withCopyFile(config);
  config = withRegisterFile(config);
  return config;
};
