export const FLOATING_TAB_BAR_PRIMARY_HEIGHT = 46;
export const FLOATING_TAB_BAR_ICON_BUTTON_SIZE = 38;
export const FLOATING_TAB_BAR_BOTTOM_GAP = -6;
export const FLOATING_TAB_BAR_GYMS_SIDE_MARGIN = 10;
export const FLOATING_TAB_BAR_SIDE_MARGIN = 10;
export const FLOATING_TAB_BAR_VERTICAL_PADDING = 12;
export const FLOATING_TAB_BAR_TOTAL_HEIGHT =
  FLOATING_TAB_BAR_PRIMARY_HEIGHT + FLOATING_TAB_BAR_VERTICAL_PADDING * 2;
export const FLOATING_TAB_BAR_STACK_SPACING =
  FLOATING_TAB_BAR_TOTAL_HEIGHT + FLOATING_TAB_BAR_BOTTOM_GAP - 1;
