// src/features/mapscreen/mapstyles/index.ts
// Bundled paper basemaps (generated by scripts/mapstyle/build.mjs — edit the
// PARAMS there and rerun; never hand-edit the JSON artifacts). Serialized
// once at module load for MapView's styleJSON prop. Shared by the main map
// and the route-detail mini map so the app renders ONE basemap look.
import outdoorsPaperStyle from './outdoors-paper.json';
import darkPaperStyle from './dark-paper.json';

export const OUTDOORS_PAPER_JSON = JSON.stringify(outdoorsPaperStyle);
export const DARK_PAPER_JSON = JSON.stringify(darkPaperStyle);
